'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var GETH_RPC = exports.GETH_RPC = 'http://localhost:8545';

var STORAGE_KEY_PREFIX = exports.STORAGE_KEY_PREFIX = 'resume.ethereum.demo.';

var AGENT_ABI_KEY = exports.AGENT_ABI_KEY = STORAGE_KEY_PREFIX + 'agent.abi';
var ACCOUNT_UNLOCK_DURATION = exports.ACCOUNT_UNLOCK_DURATION = 1800;
var TRANSFER_ETHER = exports.TRANSFER_ETHER = 5;
var MIN_ETHER_RATE = exports.MIN_ETHER_RATE = 0.2;

var SYSTEM_ACCOUNT_KEY = exports.SYSTEM_ACCOUNT_KEY = STORAGE_KEY_PREFIX + 'system.account';
var SYSTEM_CONTRACT_NAME = exports.SYSTEM_CONTRACT_NAME = 'systemContract';
var SYSTEM_AGENT_ADDRESS_KEY = exports.SYSTEM_AGENT_ADDRESS_KEY = STORAGE_KEY_PREFIX + 'system.agent.address';

var APPLICANT_ACCOUNT_KEY = exports.APPLICANT_ACCOUNT_KEY = STORAGE_KEY_PREFIX + 'applicant.account.';
var APPLICANT_PROFILE_KEY = exports.APPLICANT_PROFILE_KEY = STORAGE_KEY_PREFIX + 'applicant.profile.';
var APPLICANT_CONTRACT_NAME = exports.APPLICANT_CONTRACT_NAME = 'applicantContract';
var APPLICANT_AGENT_ADDRESS_KEY = exports.APPLICANT_AGENT_ADDRESS_KEY = STORAGE_KEY_PREFIX + 'applicant.agent.address.';
var APPLICANT_RESUMES_KEY = exports.APPLICANT_RESUMES_KEY = STORAGE_KEY_PREFIX + 'applicant.resumes.';
var APPLICANT_APPROVAL_RECV_HASHES = exports.APPLICANT_APPROVAL_RECV_HASHES = STORAGE_KEY_PREFIX + 'applicant.approval.recv.hashes.';
var APPLICANT_PERMISSIONS_KEY = exports.APPLICANT_PERMISSIONS_KEY = STORAGE_KEY_PREFIX + 'applicant.permissions.';

var ORGANIZATION_ACCOUNT_KEY = exports.ORGANIZATION_ACCOUNT_KEY = STORAGE_KEY_PREFIX + 'organization.account.';
var ORGANIZATION_PROFILE_KEY = exports.ORGANIZATION_PROFILE_KEY = STORAGE_KEY_PREFIX + 'organization.profile.';
var ORGANIZATION_CONTRACT_NAME = exports.ORGANIZATION_CONTRACT_NAME = 'organizationContract';
var ORGANIZATION_AGENT_ADDRESS_KEY = exports.ORGANIZATION_AGENT_ADDRESS_KEY = STORAGE_KEY_PREFIX + 'organization.agent.address.';
var ORGANIZATION_APPLICANT_PROFILE_KEY = exports.ORGANIZATION_APPLICANT_PROFILE_KEY = STORAGE_KEY_PREFIX + 'organization.applicant.profile.';
var ORGANIZATION_APPROVALS_KEY = exports.ORGANIZATION_APPROVALS_KEY = STORAGE_KEY_PREFIX + 'organization.approvals.';
var ORGANIZATION_APPROVAL_RECV_HASHES = exports.ORGANIZATION_APPROVAL_RECV_HASHES = STORAGE_KEY_PREFIX + 'organization.approval.recv.hashes.';
var ORGANIZATION_PERMISSIONS_KEY = exports.ORGANIZATION_PERMISSIONS_KEY = STORAGE_KEY_PREFIX + 'organization.permissions.';
var ORGANIZATION_PERMISSION_RECV_HASHES = exports.ORGANIZATION_PERMISSION_RECV_HASHES = STORAGE_KEY_PREFIX + 'organization.permission.recv.hashes.';

var TOPIC_NAME = exports.TOPIC_NAME = STORAGE_KEY_PREFIX + 'topic';
var APPROVAL_TOPIC_NAME = exports.APPROVAL_TOPIC_NAME = STORAGE_KEY_PREFIX + 'approval.topic';
var PERMISSION_TOPIC_NAME = exports.PERMISSION_TOPIC_NAME = STORAGE_KEY_PREFIX + 'permission.topic';
var APPROVAL_TOPIC2_NAME = exports.APPROVAL_TOPIC2_NAME = STORAGE_KEY_PREFIX + 'approval.topic2';
var PERMISSION_TOPIC2_NAME = exports.PERMISSION_TOPIC2_NAME = STORAGE_KEY_PREFIX + 'permission.topic2';
var TOPIC_MSG_TTL = exports.TOPIC_MSG_TTL = 2592000;